/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatorioVisualizarRouteImport } from './routes/relatorio-visualizar'
import { Route as NovoRouteImport } from './routes/novo'
import { Route as IndexRouteImport } from './routes/index'

const RelatorioVisualizarRoute = RelatorioVisualizarRouteImport.update({
  id: '/relatorio-visualizar',
  path: '/relatorio-visualizar',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoRoute = NovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/novo': typeof NovoRoute
  '/relatorio-visualizar': typeof RelatorioVisualizarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/novo': typeof NovoRoute
  '/relatorio-visualizar': typeof RelatorioVisualizarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/novo': typeof NovoRoute
  '/relatorio-visualizar': typeof RelatorioVisualizarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/novo' | '/relatorio-visualizar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/novo' | '/relatorio-visualizar'
  id: '__root__' | '/' | '/novo' | '/relatorio-visualizar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NovoRoute: typeof NovoRoute
  RelatorioVisualizarRoute: typeof RelatorioVisualizarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorio-visualizar': {
      id: '/relatorio-visualizar'
      path: '/relatorio-visualizar'
      fullPath: '/relatorio-visualizar'
      preLoaderRoute: typeof RelatorioVisualizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo': {
      id: '/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof NovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NovoRoute: NovoRoute,
  RelatorioVisualizarRoute: RelatorioVisualizarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
